@echo off
setlocal
cd /d "%~dp0"

echo.
echo ASR inference service - setup
echo ==============================
echo.
echo Select model loading mode:
echo   1) PEFT adapter + base (HF LoRA on Whisper)
echo   2) Merged / full single HF checkpoint
echo   3) Faster Whisper (CTranslate2)
echo   4) Default (no ASR_* in .env - use app/core/config.py defaults)
echo.
set "MODE_CHOICE="
set /p MODE_CHOICE="Enter 1-4 [4]: "
if "%MODE_CHOICE%"=="" set "MODE_CHOICE=4"

if exist .env (
  for /f "delims=" %%t in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMddHHmmss"') do set "TS=%%t"
  copy /Y .env ".env.backup.%TS%" >nul
  echo Backed up existing .env to .env.backup.%TS%
)

if "%MODE_CHOICE%"=="1" goto WRITE_PEFT
if "%MODE_CHOICE%"=="2" goto WRITE_MERGED
if "%MODE_CHOICE%"=="3" goto WRITE_FASTER
goto WRITE_DEFAULT

:WRITE_PEFT
(
  echo # Generated by setup.bat - PEFT adapter + base
  echo ASR_MODEL_KIND=peft
  echo ASR_MODEL_ID=SPEAK-ASR/whisper-si-exp-10-medium-all
  echo # ASR_BASE_MODEL_ID=openai/whisper-medium
  echo ASR_MERGE_PEFT_ADAPTER=true
  echo ASR_DEVICE=auto
  echo ASR_CUDA_DTYPE=float16
  echo ASR_LANGUAGE_HINT=si
  echo ASR_TASK=transcribe
) > .env
echo Wrote .env for PEFT mode.
goto AFTER_ENV

:WRITE_MERGED
(
  echo # Generated by setup.bat - merged / full checkpoint ^(edit ASR_MODEL_ID^)
  echo ASR_MODEL_KIND=merged
  echo ASR_MODEL_ID=your-org/your-merged-whisper-medium-si
  echo ASR_DEVICE=auto
  echo ASR_CUDA_DTYPE=float16
  echo ASR_LANGUAGE_HINT=si
  echo ASR_TASK=transcribe
) > .env
echo Wrote .env for merged mode. Edit ASR_MODEL_ID in .env before running.
goto AFTER_ENV

:WRITE_FASTER
(
  echo # Generated by setup.bat - faster-whisper / CTranslate2
  echo ASR_MODEL_KIND=faster_whisper
  echo ASR_MODEL_ID=irudachirath/faster-whisper-medium-si-exp10-fp16
  echo ASR_DEVICE=auto
  echo ASR_FASTER_WHISPER_CUDA_COMPUTE_TYPE=float16
  echo ASR_FASTER_WHISPER_CPU_COMPUTE_TYPE=int8
  echo ASR_LANGUAGE_HINT=si
  echo ASR_TASK=transcribe
) > .env
echo Wrote .env for faster_whisper mode.
goto AFTER_ENV

:WRITE_DEFAULT
(
  echo # Generated by setup.bat - default mode
  echo # No ASR_* overrides; pydantic uses built-in defaults ^(see app/core/config.py^).
) > .env
echo Wrote minimal .env (default app settings).
goto AFTER_ENV

:AFTER_ENV

echo.
set "LAUNCH_PY=python"
set "PY_EXTRA="
where python >nul 2>&1
if errorlevel 1 (
  set "LAUNCH_PY=py"
  set "PY_EXTRA=-3"
  where py >nul 2>&1
  if errorlevel 1 (
    echo Error: Python not found on PATH.
    exit /b 1
  )
)

echo Using: %LAUNCH_PY% %PY_EXTRA%
if "%PY_EXTRA%"=="" (
  %LAUNCH_PY% --version
) else (
  %LAUNCH_PY% %PY_EXTRA% --version
)
echo.
set "DO_VENV=Y"
set /p DO_VENV="Create/update virtualenv in .venv? [Y/n]: "
if /i "%DO_VENV%"=="n" (
  echo Skipped venv. Ensure your environment has dependencies from requirements.txt
  goto PRINT_RUN
)

if "%PY_EXTRA%"=="" (
  %LAUNCH_PY% -m venv .venv
) else (
  %LAUNCH_PY% %PY_EXTRA% -m venv .venv
)
if errorlevel 1 (
  echo Failed to create venv.
  exit /b 1
)
call ".venv\Scripts\activate.bat"
python -m pip install --upgrade pip
if errorlevel 1 exit /b 1

set "DO_CUDA=N"
set /p DO_CUDA="Install PyTorch CUDA 12.1 wheel before other deps? [y/N]: "
if /i "%DO_CUDA%"=="y" (
  python -m pip install --index-url https://download.pytorch.org/whl/cu121 "torch>=2.2"
  if errorlevel 1 exit /b 1
)
python -m pip install -r requirements.txt
if errorlevel 1 exit /b 1
echo Dependencies installed inside .venv

:PRINT_RUN
echo.
echo ==============================
echo Setup finished (server not started).
echo.
if /i "%DO_VENV%"=="n" (
  echo Run the app (after activating your own venv if needed^):
  echo.
  echo   uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
) else (
  echo Run the app:
  echo.
  echo   .venv\Scripts\activate
  echo   uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
)
echo.
endlocal
exit /b 0
