#!/usr/bin/env bash
# Interactive setup: choose ASR model mode, create venv, install dependencies.
# Does not start the server — prints the run command at the end.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

echo ""
echo "ASR inference service — setup"
echo "=============================="
echo ""
echo "Select model loading mode:"
echo "  1) PEFT adapter + base (HF LoRA on Whisper)"
echo "  2) Merged / full single HF checkpoint"
echo "  3) Faster Whisper (CTranslate2)"
echo "  4) Default (no ASR_* in .env — use app/core/config.py defaults)"
echo ""
read -r -p "Enter 1–4 [4]: " MODE_CHOICE
MODE_CHOICE="${MODE_CHOICE:-4}"

backup_env() {
  if [[ -f .env ]]; then
    cp -f .env ".env.backup.$(date +%Y%m%d%H%M%S)"
    echo "Backed up existing .env to .env.backup.*"
  fi
}

write_env_peft() {
  cat > .env << 'EOF'
# Generated by setup.sh — PEFT adapter + base
ASR_MODEL_KIND=peft
ASR_MODEL_ID=SPEAK-ASR/whisper-si-exp-10-medium-all
# ASR_BASE_MODEL_ID=openai/whisper-medium
ASR_MERGE_PEFT_ADAPTER=true
ASR_DEVICE=auto
ASR_CUDA_DTYPE=float16
ASR_LANGUAGE_HINT=si
ASR_TASK=transcribe
EOF
}

write_env_merged() {
  cat > .env << 'EOF'
# Generated by setup.sh — merged / full checkpoint (edit ASR_MODEL_ID)
ASR_MODEL_KIND=merged
ASR_MODEL_ID=your-org/your-merged-whisper-medium-si
ASR_DEVICE=auto
ASR_CUDA_DTYPE=float16
ASR_LANGUAGE_HINT=si
ASR_TASK=transcribe
EOF
}

write_env_faster() {
  cat > .env << 'EOF'
# Generated by setup.sh — faster-whisper / CTranslate2
ASR_MODEL_KIND=faster_whisper
ASR_MODEL_ID=irudachirath/faster-whisper-medium-si-exp10-fp16
ASR_DEVICE=auto
ASR_FASTER_WHISPER_CUDA_COMPUTE_TYPE=float16
ASR_FASTER_WHISPER_CPU_COMPUTE_TYPE=int8
ASR_LANGUAGE_HINT=si
ASR_TASK=transcribe
EOF
}

write_env_default() {
  cat > .env << 'EOF'
# Generated by setup.sh — default mode
# No ASR_* overrides; pydantic uses built-in defaults (see app/core/config.py).
EOF
}

case "$MODE_CHOICE" in
  1)
    backup_env
    write_env_peft
    echo "Wrote .env for PEFT mode."
    ;;
  2)
    backup_env
    write_env_merged
    echo "Wrote .env for merged mode. Edit ASR_MODEL_ID in .env before running."
    ;;
  3)
    backup_env
    write_env_faster
    echo "Wrote .env for faster_whisper mode."
    ;;
  4|*)
    backup_env
    write_env_default
    echo "Wrote minimal .env (default app settings)."
    ;;
esac

echo ""
PY=""
if command -v python3 >/dev/null 2>&1; then
  PY="python3"
elif command -v python >/dev/null 2>&1; then
  PY="python"
else
  echo "Error: neither python3 nor python found on PATH."
  exit 1
fi

echo "Using interpreter: $PY ($("$PY" --version 2>&1))"
echo ""
read -r -p "Create/update virtualenv in .venv? [Y/n]: " DO_VENV
DO_VENV="${DO_VENV:-Y}"
if [[ "$DO_VENV" =~ ^[Nn]$ ]]; then
  echo "Skipped venv. Ensure your environment has dependencies from requirements.txt"
else
  "$PY" -m venv .venv
  # shellcheck disable=SC1091
  source .venv/bin/activate
  python -m pip install --upgrade pip
  echo ""
  read -r -p "Install PyTorch CUDA 12.1 wheel before other deps? [y/N]: " DO_CUDA
  if [[ "${DO_CUDA:-}" =~ ^[Yy]$ ]]; then
    python -m pip install --index-url https://download.pytorch.org/whl/cu121 "torch>=2.2"
  fi
  python -m pip install -r requirements.txt
  echo "Dependencies installed inside .venv"
fi

echo ""
echo "=============================="
echo "Setup finished (server not started)."
echo ""
if [[ "${DO_VENV:-}" =~ ^[Nn]$ ]]; then
  echo "Run the app (after activating your own venv if needed):"
  echo ""
  echo "  uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
else
  echo "Run the app:"
  echo ""
  echo "  source .venv/bin/activate"
  echo "  uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
fi
echo ""
