@echo off
setlocal EnableDelayedExpansion
cd /d "%~dp0"

echo.
echo ASR inference service - setup
echo ==============================
echo.
echo Select model loading mode:
echo   1) PEFT adapter + base (HF LoRA on Whisper)
echo   2) Merged / full single HF checkpoint
echo   3) Faster Whisper (CTranslate2)
echo   4) Default (no ASR_* in .env - use app/core/config.py defaults)
echo.
set "MODE_CHOICE="
set /p MODE_CHOICE="Enter 1-4 [4]: "
if "%MODE_CHOICE%"=="" set "MODE_CHOICE=4"

if exist .env (
  for /f "delims=" %%t in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMddHHmmss"') do set "TS=%%t"
  copy /Y .env ".env.backup.%TS%" >nul
  echo Backed up existing .env to .env.backup.%TS%
)

if "%MODE_CHOICE%"=="1" goto WRITE_PEFT
if "%MODE_CHOICE%"=="2" goto WRITE_MERGED
if "%MODE_CHOICE%"=="3" goto WRITE_FASTER
goto WRITE_DEFAULT

:WRITE_PEFT
echo.
echo PEFT / adapter - values default like config/transformers-adapter.env.example
echo Press Enter to accept each [default].
echo.
set "V_MODEL_ID="
set /p V_MODEL_ID="ASR_MODEL_ID [SPEAK-ASR/whisper-si-exp-10-medium-all]: "
if "!V_MODEL_ID!"=="" set "V_MODEL_ID=SPEAK-ASR/whisper-si-exp-10-medium-all"

set "V_BASE="
set /p V_BASE="ASR_BASE_MODEL_ID optional (Enter to omit): "

set "V_MERGE="
set /p V_MERGE="ASR_MERGE_PEFT_ADAPTER [true]: "
if "!V_MERGE!"=="" set "V_MERGE=true"

set "V_DEVICE="
set /p V_DEVICE="ASR_DEVICE [auto]: "
if "!V_DEVICE!"=="" set "V_DEVICE=auto"

set "V_CUDA="
set /p V_CUDA="ASR_CUDA_DTYPE [float16]: "
if "!V_CUDA!"=="" set "V_CUDA=float16"

set "V_LANG="
set /p V_LANG="ASR_LANGUAGE_HINT [si]: "
if "!V_LANG!"=="" set "V_LANG=si"

set "V_TASK="
set /p V_TASK="ASR_TASK [transcribe]: "
if "!V_TASK!"=="" set "V_TASK=transcribe"

> .env (
  echo # Generated by setup.bat - PEFT adapter + base
  echo ASR_MODEL_KIND=peft
  echo ASR_MODEL_ID=!V_MODEL_ID!
)
if not "!V_BASE!"=="" (
  (echo ASR_BASE_MODEL_ID=!V_BASE!)>>.env
)
>>.env (
  echo ASR_MERGE_PEFT_ADAPTER=!V_MERGE!
  echo ASR_DEVICE=!V_DEVICE!
  echo ASR_CUDA_DTYPE=!V_CUDA!
  echo ASR_LANGUAGE_HINT=!V_LANG!
  echo ASR_TASK=!V_TASK!
)
echo Wrote .env for PEFT mode.
goto AFTER_ENV

:WRITE_MERGED
echo.
echo Merged / full checkpoint - like config/transformers-merged-full.env.example
echo.
set "V_MODEL_ID="
set /p V_MODEL_ID="ASR_MODEL_ID [your-org/your-merged-whisper-medium-si]: "
if "!V_MODEL_ID!"=="" set "V_MODEL_ID=your-org/your-merged-whisper-medium-si"

set "V_DEVICE="
set /p V_DEVICE="ASR_DEVICE [auto]: "
if "!V_DEVICE!"=="" set "V_DEVICE=auto"

set "V_CUDA="
set /p V_CUDA="ASR_CUDA_DTYPE [float16]: "
if "!V_CUDA!"=="" set "V_CUDA=float16"

set "V_LANG="
set /p V_LANG="ASR_LANGUAGE_HINT [si]: "
if "!V_LANG!"=="" set "V_LANG=si"

set "V_TASK="
set /p V_TASK="ASR_TASK [transcribe]: "
if "!V_TASK!"=="" set "V_TASK=transcribe"

> .env (
  echo # Generated by setup.bat - merged / full HF checkpoint
  echo ASR_MODEL_KIND=merged
  echo ASR_MODEL_ID=!V_MODEL_ID!
  echo ASR_DEVICE=!V_DEVICE!
  echo ASR_CUDA_DTYPE=!V_CUDA!
  echo ASR_LANGUAGE_HINT=!V_LANG!
  echo ASR_TASK=!V_TASK!
)
echo Wrote .env for merged mode.
goto AFTER_ENV

:WRITE_FASTER
echo.
echo Faster Whisper / CTranslate2 - like config/faster-whisper-ct2.env.example
echo.
set "V_MODEL_ID="
set /p V_MODEL_ID="ASR_MODEL_ID [irudachirath/faster-whisper-medium-si-exp10-fp16]: "
if "!V_MODEL_ID!"=="" set "V_MODEL_ID=irudachirath/faster-whisper-medium-si-exp10-fp16"

set "V_DEVICE="
set /p V_DEVICE="ASR_DEVICE [auto]: "
if "!V_DEVICE!"=="" set "V_DEVICE=auto"

set "V_CT_CUDA="
set /p V_CT_CUDA="ASR_FASTER_WHISPER_CUDA_COMPUTE_TYPE [float16]: "
if "!V_CT_CUDA!"=="" set "V_CT_CUDA=float16"

set "V_CT_CPU="
set /p V_CT_CPU="ASR_FASTER_WHISPER_CPU_COMPUTE_TYPE [int8]: "
if "!V_CT_CPU!"=="" set "V_CT_CPU=int8"

set "V_BEAM="
set /p V_BEAM="ASR_FASTER_WHISPER_BEAM_SIZE [1]: "
if "!V_BEAM!"=="" set "V_BEAM=1"

set "V_LANG="
set /p V_LANG="ASR_LANGUAGE_HINT [si]: "
if "!V_LANG!"=="" set "V_LANG=si"

set "V_TASK="
set /p V_TASK="ASR_TASK [transcribe]: "
if "!V_TASK!"=="" set "V_TASK=transcribe"

> .env (
  echo # Generated by setup.bat - faster-whisper / CTranslate2
  echo ASR_MODEL_KIND=faster_whisper
  echo ASR_MODEL_ID=!V_MODEL_ID!
  echo ASR_DEVICE=!V_DEVICE!
  echo ASR_FASTER_WHISPER_CUDA_COMPUTE_TYPE=!V_CT_CUDA!
  echo ASR_FASTER_WHISPER_CPU_COMPUTE_TYPE=!V_CT_CPU!
  echo ASR_FASTER_WHISPER_BEAM_SIZE=!V_BEAM!
  echo ASR_LANGUAGE_HINT=!V_LANG!
  echo ASR_TASK=!V_TASK!
)
echo Wrote .env for faster_whisper mode.
goto AFTER_ENV

:WRITE_DEFAULT
(
  echo # Generated by setup.bat - default mode
  echo # No ASR_* overrides; pydantic uses built-in defaults ^(see app/core/config.py^).
) > .env
echo Wrote minimal .env (default app settings).
goto AFTER_ENV

:AFTER_ENV

echo.
set "DO_PP="
set /p DO_PP="Add optional speaker diarization (pyannote) vars to .env? [y/N]: "
if /i "!DO_PP!"=="y" (
  echo Accept the model terms on Hugging Face for the diarization pipeline.
  set "V_HF="
  set /p V_HF="ASR_HF_TOKEN (optional; else use HF_TOKEN / HUGGING_FACE_HUB_TOKEN): "
  set "V_DIA_MODEL="
  set /p V_DIA_MODEL="ASR_DIARIZATION_MODEL_ID [pyannote/speaker-diarization-community-1]: "
  if "!V_DIA_MODEL!"=="" set "V_DIA_MODEL=pyannote/speaker-diarization-community-1"
  set "V_DIA_DEF="
  set /p V_DIA_DEF="ASR_POSTPROCESSING_DIARIZATION_DEFAULT [false]: "
  if "!V_DIA_DEF!"=="" set "V_DIA_DEF=false"
  set "V_NOISE_DEF="
  set /p V_NOISE_DEF="ASR_POSTPROCESSING_NOISE_REMOVAL_DEFAULT [false]: "
  if "!V_NOISE_DEF!"=="" set "V_NOISE_DEF=false"
  echo.>>.env
  echo # Optional: pyannote speaker diarization (see config/*.env.example)>>.env
  if not "!V_HF!"=="" (
    (echo ASR_HF_TOKEN=!V_HF!)>>.env
  )
  (echo ASR_DIARIZATION_MODEL_ID=!V_DIA_MODEL!)>>.env
  (echo ASR_POSTPROCESSING_DIARIZATION_DEFAULT=!V_DIA_DEF!)>>.env
  (echo ASR_POSTPROCESSING_NOISE_REMOVAL_DEFAULT=!V_NOISE_DEF!)>>.env
  echo Appended postprocessing variables to .env
)

echo.
set "LAUNCH_PY=python"
set "PY_EXTRA="
where python >nul 2>&1
if errorlevel 1 (
  set "LAUNCH_PY=py"
  set "PY_EXTRA=-3"
  where py >nul 2>&1
  if errorlevel 1 (
    echo Error: Python not found on PATH.
    exit /b 1
  )
)

echo Using: %LAUNCH_PY% %PY_EXTRA%
if "%PY_EXTRA%"=="" (
  %LAUNCH_PY% --version
) else (
  %LAUNCH_PY% %PY_EXTRA% --version
)
echo.
set "DO_VENV=Y"
set /p DO_VENV="Create/update virtualenv in .venv? [Y/n]: "
if /i "%DO_VENV%"=="n" (
  echo Skipped venv. Ensure your environment has dependencies from requirements.txt
  goto PRINT_RUN
)

if "%PY_EXTRA%"=="" (
  %LAUNCH_PY% -m venv .venv
) else (
  %LAUNCH_PY% %PY_EXTRA% -m venv .venv
)
if errorlevel 1 (
  echo Failed to create venv.
  exit /b 1
)
call ".venv\Scripts\activate.bat"
python -m pip install --upgrade pip
if errorlevel 1 exit /b 1

set "DO_CUDA=N"
set /p DO_CUDA="Install PyTorch CUDA 12.1 wheel before other deps? [y/N]: "
if /i "%DO_CUDA%"=="y" (
  python -m pip install --index-url https://download.pytorch.org/whl/cu121 "torch>=2.2"
  if errorlevel 1 exit /b 1
)
python -m pip install -r requirements.txt
if errorlevel 1 exit /b 1
echo Dependencies installed inside .venv

:PRINT_RUN
echo.
echo ==============================
echo Setup finished (server not started).
echo.
if /i "%DO_VENV%"=="n" (
  echo Run the app (after activating your own venv if needed^):
  echo.
  echo   uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
) else (
  echo Run the app:
  echo.
  echo   .venv\Scripts\activate
  echo   uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
)
echo.
endlocal
exit /b 0
