#!/usr/bin/env bash
# Interactive setup: choose ASR model mode, prompt for .env values, venv + deps.
# Does not start the server — prints the run command at the end.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

prompt_with_default() {
  local msg="$1"
  local def="$2"
  local val
  read -r -p "${msg} [${def}]: " val || true
  echo "${val:-$def}"
}

prompt_optional_blank() {
  local msg="$1"
  local val
  read -r -p "${msg} (Enter to omit): " val || true
  echo "${val:-}"
}

echo ""
echo "ASR inference service — setup"
echo "=============================="
echo ""
echo "Select model loading mode:"
echo "  1) PEFT adapter + base (HF LoRA on Whisper)"
echo "  2) Merged / full single HF checkpoint"
echo "  3) Faster Whisper (CTranslate2)"
echo "  4) Default (no ASR_* in .env — use app/core/config.py defaults)"
echo ""
read -r -p "Enter 1–4 [4]: " MODE_CHOICE
MODE_CHOICE="${MODE_CHOICE:-4}"

backup_env() {
  if [[ -f .env ]]; then
    cp -f .env ".env.backup.$(date +%Y%m%d%H%M%S)"
    echo "Backed up existing .env to .env.backup.*"
  fi
}

write_env_peft_interactive() {
  echo ""
  echo "PEFT / adapter — values match config/transformers-adapter.env.example defaults."
  echo "Press Enter to accept each [default]."
  echo ""
  local model_id base merge device cuda_dtype lang task
  model_id="$(prompt_with_default "ASR_MODEL_ID" "SPEAK-ASR/whisper-si-exp-10-medium-all")"
  base="$(prompt_optional_blank "ASR_BASE_MODEL_ID (optional; else adapter_config.json base)")"
  merge="$(prompt_with_default "ASR_MERGE_PEFT_ADAPTER" "true")"
  device="$(prompt_with_default "ASR_DEVICE" "auto")"
  cuda_dtype="$(prompt_with_default "ASR_CUDA_DTYPE" "float16")"
  lang="$(prompt_with_default "ASR_LANGUAGE_HINT" "si")"
  task="$(prompt_with_default "ASR_TASK" "transcribe")"

  {
    echo "# Generated by setup.sh — PEFT adapter + base"
    echo "ASR_MODEL_KIND=peft"
    echo "ASR_MODEL_ID=${model_id}"
    if [[ -n "${base}" ]]; then
      echo "ASR_BASE_MODEL_ID=${base}"
    fi
    echo "ASR_MERGE_PEFT_ADAPTER=${merge}"
    echo "ASR_DEVICE=${device}"
    echo "ASR_CUDA_DTYPE=${cuda_dtype}"
    echo "ASR_LANGUAGE_HINT=${lang}"
    echo "ASR_TASK=${task}"
  } > .env
}

write_env_merged_interactive() {
  echo ""
  echo "Merged / full checkpoint — values match config/transformers-merged-full.env.example defaults."
  echo ""
  local model_id device cuda_dtype lang task
  model_id="$(prompt_with_default "ASR_MODEL_ID" "your-org/your-merged-whisper-medium-si")"
  device="$(prompt_with_default "ASR_DEVICE" "auto")"
  cuda_dtype="$(prompt_with_default "ASR_CUDA_DTYPE" "float16")"
  lang="$(prompt_with_default "ASR_LANGUAGE_HINT" "si")"
  task="$(prompt_with_default "ASR_TASK" "transcribe")"

  {
    echo "# Generated by setup.sh — merged / full HF checkpoint"
    echo "ASR_MODEL_KIND=merged"
    echo "ASR_MODEL_ID=${model_id}"
    echo "ASR_DEVICE=${device}"
    echo "ASR_CUDA_DTYPE=${cuda_dtype}"
    echo "ASR_LANGUAGE_HINT=${lang}"
    echo "ASR_TASK=${task}"
  } > .env
}

write_env_faster_interactive() {
  echo ""
  echo "Faster Whisper / CTranslate2 — values match config/faster-whisper-ct2.env.example defaults."
  echo ""
  local model_id device ct_cuda ct_cpu beam lang task
  model_id="$(prompt_with_default "ASR_MODEL_ID" "irudachirath/faster-whisper-medium-si-exp10-fp16")"
  device="$(prompt_with_default "ASR_DEVICE" "auto")"
  ct_cuda="$(prompt_with_default "ASR_FASTER_WHISPER_CUDA_COMPUTE_TYPE" "float16")"
  ct_cpu="$(prompt_with_default "ASR_FASTER_WHISPER_CPU_COMPUTE_TYPE" "int8")"
  beam="$(prompt_with_default "ASR_FASTER_WHISPER_BEAM_SIZE" "1")"
  lang="$(prompt_with_default "ASR_LANGUAGE_HINT" "si")"
  task="$(prompt_with_default "ASR_TASK" "transcribe")"

  {
    echo "# Generated by setup.sh — faster-whisper / CTranslate2"
    echo "ASR_MODEL_KIND=faster_whisper"
    echo "ASR_MODEL_ID=${model_id}"
    echo "ASR_DEVICE=${device}"
    echo "ASR_FASTER_WHISPER_CUDA_COMPUTE_TYPE=${ct_cuda}"
    echo "ASR_FASTER_WHISPER_CPU_COMPUTE_TYPE=${ct_cpu}"
    echo "ASR_FASTER_WHISPER_BEAM_SIZE=${beam}"
    echo "ASR_LANGUAGE_HINT=${lang}"
    echo "ASR_TASK=${task}"
  } > .env
}

write_env_default() {
  cat > .env << 'EOF'
# Generated by setup.sh — default mode
# No ASR_* overrides; pydantic uses built-in defaults (see app/core/config.py).
EOF
}

append_hf_token() {
  echo ""
  echo "HuggingFace Hub token — required for pyannote diarization (gated models)."
  echo "Get yours at https://hf.co/settings/tokens"
  echo "Also accept user conditions for both sub-models before starting:"
  echo "  https://hf.co/pyannote/speaker-diarization-3.1"
  echo "  https://hf.co/pyannote/segmentation-3.0"
  echo ""
  local hf_token
  hf_token="$(prompt_optional_blank "HF_TOKEN")"
  if [[ -n "${hf_token}" ]]; then
    {
      echo ""
      echo "# HuggingFace Hub authentication (required for gated models)"
      echo "HF_TOKEN=${hf_token}"
    } >> .env
    echo "Added HF_TOKEN to .env"
  else
    {
      echo ""
      echo "# HF_TOKEN=hf_xxxxxxxxxxxx  (set to access gated models e.g. pyannote diarization)"
    } >> .env
    echo "Skipped HF_TOKEN (uncomment and fill in .env later if you need gated models)."
  fi
}

case "$MODE_CHOICE" in
  1)
    backup_env
    write_env_peft_interactive
    echo "Wrote .env for PEFT mode."
    ;;
  2)
    backup_env
    write_env_merged_interactive
    echo "Wrote .env for merged mode."
    ;;
  3)
    backup_env
    write_env_faster_interactive
    echo "Wrote .env for faster_whisper mode."
    ;;
  4|*)
    backup_env
    write_env_default
    echo "Wrote minimal .env (default app settings)."
    ;;
esac

append_hf_token

echo ""
PY=""
if command -v python3 >/dev/null 2>&1; then
  PY="python3"
elif command -v python >/dev/null 2>&1; then
  PY="python"
else
  echo "Error: neither python3 nor python found on PATH."
  exit 1
fi

echo "Using interpreter: $PY ($("$PY" --version 2>&1))"
echo ""
read -r -p "Create/update virtualenv in .venv? [Y/n]: " DO_VENV
DO_VENV="${DO_VENV:-Y}"
if [[ "$DO_VENV" =~ ^[Nn]$ ]]; then
  echo "Skipped venv. Ensure your environment has dependencies from requirements.txt"
else
  "$PY" -m venv .venv
  # shellcheck disable=SC1091
  source .venv/bin/activate
  python -m pip install --upgrade pip
  echo ""
  read -r -p "Install PyTorch CUDA 12.1 wheel before other deps? [y/N]: " DO_CUDA
  if [[ "${DO_CUDA:-}" =~ ^[Yy]$ ]]; then
    python -m pip install --index-url https://download.pytorch.org/whl/cu121 "torch>=2.2"
  fi
  python -m pip install -r requirements.txt
  echo "Dependencies installed inside .venv"
fi

echo ""
echo "=============================="
echo "Setup finished (server not started)."
echo ""
if [[ "${DO_VENV:-}" =~ ^[Nn]$ ]]; then
  echo "Run the app (after activating your own venv if needed):"
  echo ""
  echo "  uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
else
  echo "Run the app:"
  echo ""
  echo "  source .venv/bin/activate"
  echo "  uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
fi
echo ""
